### ISSUE TITLE
Change Client Attestation JWT to SD-JWT

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-looker-oauth-attestation-based-client-authentication#20]
If we use SD-JWT instead of JWT for Client Attestation, things might be easier and its a good test case for using SD-JWT without Disclosures

**Comment by Sakurann** [comment]
SD-JWT VC as defined in [draft-terbu-sd-jwt-vc](https://github.com/vcstuff/draft-terbu-sd-jwt-vc) without SD, right? (we should differentiate with sd-jwt)

**Comment by Sakurann** [comment]
what is the use-case for the wallet attestation with selective disclosure?

**Comment by paulbastian** [comment]
we probably don't need selective disclosure. SD-JWT-VC gives some feature like easy holder-binding with tilde and key discovery etc that we would need replicate with plain JWTs

**Comment by paulbastian** [comment]
whether to rely on SD-JWT or SD-JWT-VC is yet another option to discuss

**Comment by paulbastian** [comment]
in the discussion on July 6th, it was agreed to stay with plain JWT for now
